name: 'Nightly Merge'

on:
  schedule:
    - cron:  '10 0 * * *'

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'development'

      - name: Nightly Merge (development -> master)
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          stable_branch: 'development'
          development_branch: 'master'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
